namespace Core.Models;

public enum PacketCommand : ushort
{
    Heartbeat = 0,
    AuthRequest = 1,
    AuthResponse = 2,
    ChatMessage = 101,
    MessageAck = 102,
    MessageReceipt = 103,
    MessageReceiptAck = 104,
    MessageReceiptUpdated = 105,
    MessageHistoryRequest = 106,
    MessageHistoryPage = 107,
    ConversationListRequest = 108,
    ConversationListPage = 109,
    ConversationMarkReadRequest = 110,
    ConversationMarkReadResponse = 111,
    ConversationChanged = 112,
    UnreadCountChanged = 113,
    SyncBootstrapRequest = 114,
    SyncBootstrapResponse = 115,
    ConversationSetPrefsRequest = 116,
    ConversationSetPrefsResponse = 117,
    MessageRecallRequest = 118,
    MessageRecallAck = 119,
    MessageRecalled = 120,
    TypingNotify = 121,
    TypingUpdate = 122,
    PresenceQuery = 123,
    PresenceSnapshot = 124,
    PresenceChanged = 125,
    PresenceUnwatch = 126,
    MessageEditRequest = 127,
    MessageEditAck = 128,
    MessageEdited = 129,
    // 反应（130-135）
    AddReactionRequest = 130,
    AddReactionAck = 131,
    ReactionAdded = 132,
    RemoveReactionRequest = 133,
    RemoveReactionAck = 134,
    ReactionRemoved = 135,
    // 群聊（136-151）
    CreateGroupRequest = 136,
    CreateGroupResponse = 137,
    AddGroupMembersRequest = 138,
    AddGroupMembersResponse = 139,
    RemoveGroupMemberRequest = 140,
    RemoveGroupMemberResponse = 141,
    LeaveGroupRequest = 142,
    LeaveGroupResponse = 143,
    ChangeMemberRoleRequest = 144,
    ChangeMemberRoleResponse = 145,
    ListGroupMembersRequest = 146,
    ListGroupMembersResponse = 147,
    MemberJoined = 148,
    MemberLeft = 149,
    MemberRemoved = 150,
    RoleChanged = 151,
    ConversationRead = 152,
    RelationshipListChanged = 153,
    AttachmentLifecycleChanged = 154,
    RegisterPushTokenRequest = 155,
    RegisterPushTokenResponse = 156,
    UnregisterPushTokenRequest = 157,
    UnregisterPushTokenResponse = 158,
    AttachmentFinalizeRequest = 159,
    AttachmentFinalizeResponse = 160,
    RelationshipCommandRequest = 161,
    RelationshipCommandResponse = 162,
    RelationshipListRequest = 163,
    RelationshipListResponse = 164,
    MembersAddedUpdate = 165,
    ConversationDissolvedUpdate = 166,
    Error = 500,
    HeartbeatAck = 1000
}
