// <auto-generated />
using System;
using Infrastructure.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ClientDbContext))]
    [Migration("20260730192938_OptimizeIndexes")]
    partial class OptimizeIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Core.Models.ServerEndpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastConnected")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerIpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ServerPort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServerIpAddress", "ServerPort");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("Infrastructure.Data.AuthToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AccessTokenExpires")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeviceIdHash")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RefreshTokenExpires")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("Infrastructure.Data.LocalUser", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastLoginTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PreviousLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<string>("Signature")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Infrastructure.Models.LocalAttachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttachmentId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientAttachmentId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadPath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalCachePath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalThumbnailPath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalUploadingPath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "AttachmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_attachments_owner_attid");

                    b.HasIndex("OwnerUserId", "ClientAttachmentId")
                        .HasDatabaseName("ix_attachments_owner_clientattid");

                    b.HasIndex("OwnerUserId", "MessageId")
                        .HasDatabaseName("ix_attachments_owner_msgid");

                    b.HasIndex("OwnerUserId", "Sha256")
                        .HasDatabaseName("ix_attachments_owner_sha256");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("Infrastructure.Models.LocalConversation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastMessageAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastMessagePreview")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastReadAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastReadMessageId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastSenderUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSynced")
                        .HasColumnType("TEXT");

                    b.Property<long?>("MutedUntilMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PeerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PinnedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnreadCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "ConversationId")
                        .IsUnique();

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Infrastructure.Models.LocalConversationReadState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastReadAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastReadMessageId")
                        .HasColumnType("TEXT");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnreadCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "ConversationId")
                        .IsUnique();

                    b.ToTable("ConversationReadStates");
                });

            modelBuilder.Entity("Infrastructure.Models.LocalFriend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FriendId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastMessagePreview")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSynced")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LocalUserUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MutedUntilMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PinnedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LocalUserUserId");

                    b.HasIndex("OwnerUserId", "FriendId")
                        .IsUnique();

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("Infrastructure.Models.LocalMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttachmentsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeliveredAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EditVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EditedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForwardedFromMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForwardedFromPreview")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ForwardedFromSenderUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ReadAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RecalledAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReceivedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReceiverUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReplyToMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplyToPreview")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReplyToSenderUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SenderUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "ClientMessageId");

                    b.HasIndex("OwnerUserId", "ConversationId");

                    b.HasIndex("OwnerUserId", "MessageId");

                    b.HasIndex("OwnerUserId", "ConversationId", "ReceivedAtMs")
                        .HasDatabaseName("ix_messages_owner_conv_time");

                    b.HasIndex("OwnerUserId", "ConversationId", "ReceivedAtMs", "MessageId")
                        .HasDatabaseName("ix_messages_owner_conv_time_msgid");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Infrastructure.Models.LocalOutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttachmentIdsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientMessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForwardedFromMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForwardedFromPreview")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ForwardedFromSenderUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplyToMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplyToPreview")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReplyToSenderUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TargetUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "ClientMessageId")
                        .IsUnique();

                    b.HasIndex("OwnerUserId", "Status");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("Infrastructure.Models.LocalSyncCursor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AfterMessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("AfterReceivedAtMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "ConversationId")
                        .IsUnique();

                    b.ToTable("SyncCursors");
                });

            modelBuilder.Entity("Infrastructure.Models.LocalFriend", b =>
                {
                    b.HasOne("Infrastructure.Data.LocalUser", null)
                        .WithMany("Friends")
                        .HasForeignKey("LocalUserUserId");
                });

            modelBuilder.Entity("Infrastructure.Data.LocalUser", b =>
                {
                    b.Navigation("Friends");
                });
#pragma warning restore 612, 618
        }
    }
}
